apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-credentials-refresh.name" . }}
  labels:
    {{ include "ecr-credentials-refresh.labels" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ecr-credentials-refresh.name" . }}
  labels:
    {{ include "ecr-credentials-refresh.labels" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ecr-credentials-refresh.name" . }}
  labels:
    {{ include "ecr-credentials-refresh.labels" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ecr-credentials-refresh.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ecr-credentials-refresh.name" . }}
